### ISSUE TITLE
Discovery does not work with Hazelcast 4.0

### ISSUE THREAD

**Issue by timoinstana** [bitsofinfo/hazelcast-consul-discovery-spi#33]
## Issue
The Consul discovery is not compatible with Hazelcast 4.0 as the package structure has changed for some classes. For us a test failed with

`java.lang.NoSuchMethodError: 'com.hazelcast.nio.Address com.hazelcast.spi.discovery.DiscoveryNode.getPrivateAddress()'`

as the package has changed to 

`com.hazelcast.cluster.Address`

## References
- https://docs.hazelcast.org/docs/rn/index.html
- https://github.com/hazelcast/hazelcast/pull/15172

**Comment by bitsofinfo** [comment]
@timoinstana please feel free to contribute a PR to make it compat, I'll incorporate it. I no longer use this library myself.

**Comment by amrsamii** [comment]
Hello @bitsofinfo, I solved the issue and consul is now working correctly with Hazelcast. can I make PR so that you review it?

**Comment by amrsamii** [comment]
However, there is a small problem. the <group> tag is not defined in hazelcast-config-4.0.xsd and the file is read only. I just removed the tag and everything works correctly. Is it correct to do that?
![Selection_444](https://user-images.githubusercontent.com/31626818/76401519-ab5f2f00-638a-11ea-9319-0cea99589ff4.png)

**Comment by amrsamii** [comment]
@bitsofinfo I fixed the issue and made PR, please review it. PR #34

**Comment by bitsofinfo** [comment]
thanks! i added some notes on the PR

**Comment by bitsofinfo** [comment]
@amrsamii https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/releases/tag/2.0-RC1
